services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: empresa_mvc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: