services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: empresa_mvc
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql